Repository riadvice/bbbeasy, pull requests merged in 2023-05, with the labels that each got.

#616 Specify the room name length
  bbbeasy-frontend/src/components/AddRoomForm.tsx
  bbbeasy-frontend/src/components/RoomDetails.tsx
  bbbeasy-frontend/src/locale/ar-TN.json
  bbbeasy-frontend/src/locale/en-US.json
  bbbeasy-frontend/src/locale/fr-FR.json
Labels: component: rooms

#619 improve room edit experience
  bbbeasy-frontend/src/components/RoomDetails.tsx
Labels: component: rooms, design: user experience

#621 Click outside the modal to close it
  bbbeasy-frontend/src/components/AddLabelForm.tsx
  bbbeasy-frontend/src/components/AddPresetForm.tsx
  bbbeasy-frontend/src/components/AddRoomForm.tsx
  bbbeasy-frontend/src/components/Roles.tsx
  bbbeasy-frontend/src/components/RoomPresentations.tsx
  bbbeasy-frontend/src/components/Step3Form.tsx
  bbbeasy-frontend/src/components/Users.tsx
Labels: type: enhancement

#625 update the success install message
  bbbeasy-frontend/src/locale/ar-TN.json
  bbbeasy-frontend/src/locale/en-US.json
  bbbeasy-frontend/src/locale/fr-FR.json
Labels: component: install, scope: localisation

#633 improve buttons position (popup) in bigbluebutton settings page.
  bbbeasy-frontend/src/components/Step3Form.tsx
Labels: component: presets, design: user interface

#639 The user with ID 1 is not edited
  bbbeasy-frontend/src/components/Users.tsx
Labels: component: users

#640 Fix preset name size (back-end)
  bbbeasy-backend/app/src/Actions/Presets/Add.php
Labels: component: presets

#626 Complete translation in "ar" and "fr" files.
  bbbeasy-frontend/src/locale/ar-TN.json
  bbbeasy-frontend/src/locale/en-US.json
  bbbeasy-frontend/src/locale/fr-FR.json
Labels: scope: localisation

#644 Fix label name size (back-end and front-end)
  bbbeasy-backend/app/src/Actions/Labels/Add.php
  bbbeasy-frontend/src/components/AddLabelForm.tsx
  bbbeasy-frontend/src/locale/ar-TN.json
  bbbeasy-frontend/src/locale/en-US.json
  bbbeasy-frontend/src/locale/fr-FR.json
Labels: component: labels

#656 update failed authentication messages
  bbbeasy-backend/app/src/Actions/Account/Login.php
  bbbeasy-frontend/src/App-webapp.css
  bbbeasy-frontend/src/components/auth/Login.tsx
  bbbeasy-frontend/src/locale/ar-TN.json
  bbbeasy-frontend/src/locale/en-US.json
  bbbeasy-frontend/src/locale/fr-FR.json
Labels: quality control: approved

#659 update The locale message welcome_bbbeasy
  bbbeasy-backend/app/config/access.ini
  bbbeasy-frontend/src/components/LandingPage.tsx
  bbbeasy-frontend/src/locale/ar-TN.json
  bbbeasy-frontend/src/locale/en-US.json
  bbbeasy-frontend/src/locale/fr-FR.json
Labels: quality control: approved

#654 block the installer when install endpoints is inactif
  bbbeasy-frontend/src/components/Install.tsx
  bbbeasy-frontend/src/locale/fr-FR.json
Labels: quality control: approved

#655 hide the gray preset groups
  bbbeasy-frontend/src/components/Presets.tsx
Labels: quality control: approved

#661 stop loading preset into infinite loop
  bbbeasy-frontend/src/components/AddPresetForm.tsx
  bbbeasy-frontend/src/components/AddRoomForm.tsx
Labels: component: presets, quality control: approved

#670 update branding section in the installer and branding page in the web…
  bbbeasy-backend/app/src/Actions/Account/Login.php
  bbbeasy-backend/app/src/Actions/Core/Install.php
  bbbeasy-backend/app/src/Models/Setting.php
  bbbeasy-backend/db/migrations/20220202151316_create_settings_tables.php
  bbbeasy-backend/db/migrations/20220208163949_add_default_settings_record.php
  bbbeasy-frontend/src/App-installer.css
  bbbeasy-frontend/src/App-webapp.css
  bbbeasy-frontend/src/components/Branding.tsx
  bbbeasy-frontend/src/components/Install.tsx
  bbbeasy-frontend/src/components/Step2Form.tsx
  bbbeasy-frontend/src/locale/ar-TN.json
  bbbeasy-frontend/src/locale/en-US.json
  bbbeasy-frontend/src/locale/fr-FR.json
  bbbeasy-frontend/src/types/SettingsType.ts
  bbbeasy-frontend/src/types/ThemeType.ts
Labels: quality control: approved

#684 Company branding
  bbbeasy-backend/app/src/Actions/Settings/Edit.php
  bbbeasy-backend/app/src/Models/Setting.php
  bbbeasy-frontend/src/App-installer.css
  bbbeasy-frontend/src/App-webapp.css
  bbbeasy-frontend/src/components/AddPresetForm.tsx
  bbbeasy-frontend/src/components/AddRoomForm.tsx
  bbbeasy-frontend/src/components/Branding.tsx
  bbbeasy-frontend/src/components/Presets.tsx
  bbbeasy-frontend/src/components/RoomDetails.tsx
  bbbeasy-frontend/src/components/Step2Form.tsx
  bbbeasy-frontend/yarn.lock
Labels: quality control: approved

#686 fix the ResizeObserver loop limit error
  bbbeasy-frontend/src/App.tsx
Labels: quality control: approved

#683 Click outside edit preset config modal
  bbbeasy-frontend/src/App.tsx
  bbbeasy-frontend/src/components/AddPresetForm.tsx
  bbbeasy-frontend/src/components/AddRoomForm.tsx
  bbbeasy-frontend/src/components/Presets.tsx
  bbbeasy-frontend/src/components/layout/AppSider.tsx
Labels: component: presets, quality control: approved

#698 Improve first screen wording
  bbbeasy-frontend/src/locale/ar-TN.json
  bbbeasy-frontend/src/locale/en-US.json
  bbbeasy-frontend/src/locale/fr-FR.json
Labels: component: rooms, quality control: approved

#699 fix cancel edit button
  bbbeasy-frontend/src/components/Labels.tsx
  bbbeasy-frontend/src/components/Users.tsx
Labels: quality control: approved

#707 Labels
  bbbeasy-backend/app/src/Actions/Labels/Add.php
  bbbeasy-backend/app/src/Models/Label.php
  bbbeasy-backend/app/src/Models/Preset.php
  bbbeasy-backend/app/src/Models/Role.php
  bbbeasy-backend/db/migrations/20220720114045_create_labels_table.php
  bbbeasy-frontend/yarn.lock
Labels: quality control: approved

#716 Enable social media share link button
  bbbeasy-frontend/package.json
  bbbeasy-frontend/src/components/RoomDetails.tsx
Labels: component: rooms, quality control: approved

#713 fix password compliancy in install && register && change password
  bbbeasy-backend/app/src/Actions/Account/ChangePassword.php
  bbbeasy-backend/app/src/Actions/Base.php
  bbbeasy-backend/app/src/Actions/Core/Install.php
  bbbeasy-backend/app/templates/mail/common/reset_password.phtml
  bbbeasy-backend/composer.lock
  bbbeasy-frontend/src/components/Profile.tsx
  bbbeasy-frontend/src/locale/ar-TN.json
  bbbeasy-frontend/src/locale/en-US.json
  bbbeasy-frontend/src/locale/fr-FR.json
  bbbeasy-frontend/yarn.lock
Labels: quality control: approved
