Repository riadvice/bbbeasy, pull requests merged in 2023-06, with the labels that each got.

#730 Room cards size
  bbbeasy-frontend/src/App-webapp.css
  bbbeasy-frontend/src/components/Rooms.tsx
Labels: type: enhancement, component: rooms, quality control: approved

#731 adding warning notification
  bbbeasy-backend/app/config/access.ini
  bbbeasy-backend/app/config/routes.ini
  bbbeasy-backend/app/src/Actions/Notification/WarningNotification.php
  bbbeasy-frontend/src/App-webapp.css
  bbbeasy-frontend/src/components/RoomDetails.tsx
  bbbeasy-frontend/src/components/layout/AppHeader.tsx
  bbbeasy-frontend/src/locale/ar-TN.json
  bbbeasy-frontend/src/locale/en-US.json
  bbbeasy-frontend/src/locale/fr-FR.json
  bbbeasy-frontend/src/routing/backend-config.tsx
  bbbeasy-frontend/src/services/notification.service.ts
Labels: component: notifications, component: rooms, type: new feature, status: discussing, quality control: approved

#729 Colorpicker border
  bbbeasy-frontend/src/App-installer.css
  bbbeasy-frontend/src/App-webapp.css
  bbbeasy-frontend/src/components/RoomDetails.tsx
  bbbeasy-frontend/src/components/Step2Form.tsx
  bbbeasy-frontend/src/locale/ar-TN.json
  bbbeasy-frontend/src/locale/en-US.json
  bbbeasy-frontend/src/locale/fr-FR.json
  bbbeasy-frontend/yarn.lock
Labels: quality control: approved

#741 improve Modal in preset configuration
  bbbeasy-frontend/src/App-installer.css
  bbbeasy-frontend/src/App-webapp.css
  bbbeasy-frontend/src/components/Step3Form.tsx
Labels: quality control: approved

#746 Fix switch button in preset settings
  bbbeasy-frontend/package.json
  bbbeasy-frontend/yarn.lock
Labels: quality control: approved

#740 Administration setting
  bbbeasy-backend/app/config/access.ini
  bbbeasy-backend/app/config/routes.ini
  bbbeasy-backend/app/src/Actions/Core/Install.php
  bbbeasy-backend/app/src/Actions/Settings/Edit.php
  bbbeasy-backend/app/src/Models/Setting.php
  bbbeasy-backend/db/migrations/20220202151316_create_settings_tables.php
  bbbeasy-backend/db/migrations/20220208163949_add_default_settings_record.php
  bbbeasy-backend/uploads/.gitkeep
  bbbeasy-frontend/src/App-installer.css
  bbbeasy-frontend/src/App-webapp.css
  bbbeasy-frontend/src/components/Administration.tsx
  bbbeasy-frontend/src/components/Branding.tsx
  bbbeasy-frontend/src/components/Profile.tsx
  bbbeasy-frontend/src/components/Step2Form.tsx
  bbbeasy-frontend/src/components/UserPasswordForm.tsx
  bbbeasy-frontend/src/components/layout/AppSider.tsx
  bbbeasy-frontend/src/locale/ar-TN.json
  bbbeasy-frontend/src/locale/en-US.json
  bbbeasy-frontend/src/locale/fr-FR.json
  bbbeasy-frontend/src/routing/config.tsx
  bbbeasy-frontend/src/services/menu.service.ts
  bbbeasy-frontend/src/types/SettingsType.ts
Labels: quality control: approved

#755 warning dropdown
  bbbeasy-frontend/src/App-webapp.css
  bbbeasy-frontend/src/components/layout/AppHeader.tsx
Labels: quality control: approved

#751 adding space between buttons in step2
  bbbeasy-frontend/src/App-installer.css
  bbbeasy-frontend/src/components/Install.tsx
Labels: component: install, quality control: approved

#760 Add a star next to the administrator's name
  bbbeasy-frontend/src/components/Users.tsx
Labels: component: users, quality control: approved

#763 fix bigbluebutton settings and step3 in installer
  bbbeasy-frontend/src/App-webapp.css
  bbbeasy-frontend/src/components/Install.tsx
  bbbeasy-frontend/src/components/PresetSettings.tsx
  bbbeasy-frontend/src/components/Recordings.tsx
  bbbeasy-frontend/src/components/Step3Form.tsx
  bbbeasy-frontend/src/components/layout/AppHeader.tsx
  bbbeasy-frontend/yarn.lock
Labels: quality control: approved

#764 fix "Labels are not saved when editing room"
  bbbeasy-backend/app/src/Actions/Rooms/Edit.php
Labels: component: rooms, quality control: approved
