Repository riadvice/bbbeasy, pull requests merged in 2023-08, with the labels that each got.

#853 add & fix missing validation messages in locale files
  bbbeasy-frontend/src/App-webapp.css
  bbbeasy-frontend/src/components/GuestPolicy.tsx
  bbbeasy-frontend/src/components/Presets.tsx
  bbbeasy-frontend/src/components/Rooms.tsx
  bbbeasy-frontend/src/locale/ar-TN.json
  bbbeasy-frontend/src/locale/en-US.json
  bbbeasy-frontend/src/locale/fr-FR.json
  bbbeasy-frontend/src/types/GuestPolicyType.ts
Labels: scope: compliancy, quality control: approved, technical review: approved

#854 Show edit and delete button when writing a long description
  bbbeasy-frontend/src/App-webapp.css
Labels: component: labels, quality control: approved, technical review: approved

#863 Share social links
  bbbeasy-frontend/src/components/Recordings.tsx
Labels: component: recordings, quality control: approved, technical review: approved

#879 fix resizeobserver issues
  bbbeasy-frontend/src/App.tsx
Labels: quality control: approved, technical review: approved

#882 update the room details page when open for everyone is active
  bbbeasy-frontend/src/components/RoomDetails.tsx
Labels: quality control: approved, technical review: approved

#893 Fix name size from edit Label (backend and frontend).
  bbbeasy-backend/app/src/Actions/Labels/Edit.php
  bbbeasy-frontend/src/App-webapp.css
  bbbeasy-frontend/src/components/EditableTableCell.tsx
  bbbeasy-frontend/src/components/Labels.tsx
  bbbeasy-frontend/src/components/RoomDetails.tsx
  bbbeasy-frontend/src/components/Rooms.tsx
Labels: component: labels, component: rooms, quality control: approved, technical review: approved

#796 Backend unit tests fixes
  bbbeasy-backend/.php-cs-fixer.php
  bbbeasy-backend/app/config/default.ini
  bbbeasy-backend/app/src/Actions/Core/GetLocale.php
  bbbeasy-backend/app/src/Application/Bootstrap.php
  bbbeasy-backend/app/src/Helpers/Upload.php
  bbbeasy-backend/app/src/Models/Base.php
  bbbeasy-backend/app/src/Models/ResetPasswordToken.php
  bbbeasy-backend/app/src/Models/Role.php
  bbbeasy-backend/app/src/Models/Room.php
  bbbeasy-backend/app/src/Models/User.php
  bbbeasy-backend/app/src/Utils/DataUtils.php
  bbbeasy-backend/app/src/Utils/PresetProcessor.php
  bbbeasy-backend/tests/src/Core/Statera.php
  bbbeasy-backend/tests/src/Fake/LabelFaker.php
  bbbeasy-backend/tests/src/Fake/PresetFaker.php
  bbbeasy-backend/tests/src/Fake/PresetSettingFaker.php
  bbbeasy-backend/tests/src/Fake/ResetPasswordTokenFaker.php
  bbbeasy-backend/tests/src/Fake/RoleFaker.php
  bbbeasy-backend/tests/src/Fake/RoomFaker.php
  bbbeasy-backend/tests/src/Fake/UserFaker.php
  bbbeasy-backend/tests/src/Models/LabelTest.php
  bbbeasy-backend/tests/src/Models/PresetTest.php
  bbbeasy-backend/tests/src/Models/ResetPasswordTokenTest.php
  bbbeasy-backend/tests/src/Models/RoleTest.php
  bbbeasy-backend/tests/src/Models/RoomLabelTest.php
  bbbeasy-backend/tests/src/Models/RoomTest.php
  bbbeasy-backend/tests/src/Models/SettingTest.php
  bbbeasy-backend/tests/src/Models/UserTest.php
  bbbeasy-backend/tests/src/Test/Scenario.php
Labels: test: unit testing, component: backend, scope: quality, technical review: approved
