Repository riadvice/bbbeasy, pull requests merged in 2023-09, with the labels that each got.

#901 Welcome message
  bbbeasy-backend/app/config/default.ini
  bbbeasy-backend/app/src/Data/PresetData.php
  bbbeasy-backend/app/src/Enum/Presets/General.php
  bbbeasy-backend/app/src/Utils/PresetProcessor.php
  bbbeasy-backend/tests/src/Models/RoleTest.php
  bbbeasy-frontend/src/components/auth/Login.tsx
  bbbeasy-frontend/src/locale/ar-TN.json
  bbbeasy-frontend/src/locale/en-US.json
  bbbeasy-frontend/src/locale/fr-FR.json
Labels: quality control: approved, technical review: approved

#904 Fix display rename presets when the name is too long and fix showing "no changes made" popup
  bbbeasy-frontend/src/App-webapp.css
  bbbeasy-frontend/src/components/Presets.tsx
Labels: component: presets, quality control: approved, technical review: approved

#906 edit Recording name & publish & unpublish recordings
  bbbeasy-backend/app/config/access.ini
  bbbeasy-backend/app/config/routes.ini
  bbbeasy-backend/app/src/Actions/Recordings/Edit.php
  bbbeasy-backend/app/src/Actions/Recordings/Publish.php
  bbbeasy-backend/app/src/Models/Room.php
  bbbeasy-backend/app/src/Utils/PresetProcessor.php
  bbbeasy-backend/tests/src/Models/RoleTest.php
  bbbeasy-frontend/src/App-webapp.css
  bbbeasy-frontend/src/components/Recordings.tsx
  bbbeasy-frontend/src/components/RoomDetails.tsx
  bbbeasy-frontend/src/components/RoomRecordings.tsx
  bbbeasy-frontend/src/locale/ar-TN.json
  bbbeasy-frontend/src/locale/en-US.json
  bbbeasy-frontend/src/locale/fr-FR.json
  bbbeasy-frontend/src/routing/backend-config.tsx
  bbbeasy-frontend/src/services/recordings.service.ts
Labels: quality control: approved, technical review: approved

#918 format code && Fix models integrity by using the "id" instead of "nam…
  bbbeasy-backend/app/config/access.ini
  bbbeasy-backend/app/src/Actions/Account/ChangePassword.php
  bbbeasy-backend/app/src/Actions/Labels/Add.php
  bbbeasy-backend/app/src/Actions/Labels/Edit.php
  bbbeasy-backend/app/src/Actions/Presets/Add.php
  bbbeasy-backend/app/src/Actions/Recordings/Publish.php
  bbbeasy-backend/app/src/Actions/Rooms/Add.php
  bbbeasy-backend/app/src/Models/Label.php
  bbbeasy-backend/app/src/Models/Room.php
  bbbeasy-backend/app/src/Models/User.php
  bbbeasy-backend/app/src/Utils/PresetProcessor.php
  bbbeasy-backend/app/src/Utils/SecurityUtils.php
  bbbeasy-backend/tests/src/Models/RoleTest.php
  bbbeasy-frontend/yarn.lock
Labels: quality control: approved
